export const PRODUCTS = [
  {
    id: 1,
    image: '👟',
    name: 'Running Shoes',
    price: 1999,
    currency: 'INR',
    rating: 4,
    description: 'Comfortable sports shoes for running',
    liked: true,
  },
  {
    id: 2,
    image: '🎒',
    name: 'Travel Backpack',
    price: 1499,
    currency: 'INR',
    rating: 5,
    description: 'Durable backpack for travel and daily use',
    liked: false,
  },
  {
    id: 3,
    image: '⌚',
    name: 'Smart Watch',
    price: 2999,
    currency: 'INR',
    rating: 4,
    description: 'Feature-rich smart watch with health tracking',
    liked: false,
  },
  {
    id: 4,
    image: '🎧',
    name: 'Wireless Headphones',
    price: 1799,
    currency: 'INR',
    rating: 5,
    description: 'Noise-cancelling wireless headphones',
    liked: false,
  },
];
